export const flowGScreens = [
  {
    id: 'flowG_intro',
    clearOnBack: { customRequestText: null },
    showSidebar: true,
    component: 'freetext',
    messageKey: 'flowG_intro.message',
    submitLabelKey: 'funnel.geo.submitLabel',
    freeTextCaptureKey: 'customRequestText',
    successMessageKey: 'flowG_intro.successMessage',
    successButtons: [
      { labelKey: 'flowG_intro.successButtons.sendRequest', target: 'flowG_function' },
      { personalizable: true, action: { type: 'startDemo', sourceFlow: 'flowG', sourceScreen: 'flowG_intro' } },
    ],
  },
  {
    id: 'flowG_function',
    clearOnBack: { role: null },
    showSidebar: true,
    autoCapture: { sourceFlow: 'flowG' },
    messageKey: 'flowG_function.message',
    promptKey: 'flowG_function.prompt',
    choices: [
      { labelKey: 'flowG_function.choices.security_risk', target: 'flowG_geo', capture: { key: 'role', value: 'security_risk' } },
      { labelKey: 'flowG_function.choices.legal',         target: 'flowG_geo', capture: { key: 'role', value: 'legal' } },
      { labelKey: 'flowG_function.choices.compliance',    target: 'flowG_geo', capture: { key: 'role', value: 'compliance_aml' } },
      { labelKey: 'flowG_function.choices.hr',            target: 'flowG_geo', capture: { key: 'role', value: 'HR' } },
      { labelKey: 'flowG_function.choices.management',    target: 'flowG_geo', capture: { key: 'role', value: 'management' } },
    ],
  },
  {
    id: 'flowG_geo',
    clearOnBack: { geoArea: null },
    showSidebar: true,
    promptKey: 'flowG_geo.prompt',
    choices: [
      { labelKey: 'flowG_geo.choices.switzerland',  target: 'flowG_need', capture: { key: 'geoArea', value: 'Svizzera' } },
      { labelKey: 'flowG_geo.choices.italy',        target: 'flowG_need', capture: { key: 'geoArea', value: 'Italia' } },
      { labelKey: 'flowG_geo.choices.europe',       target: 'flowG_need', capture: { key: 'geoArea', value: 'Europa' } },
      { labelKey: 'flowG_geo.choices.middleEast',   target: 'flowG_need', capture: { key: 'geoArea', value: 'Medio Oriente' } },
      { labelKey: 'flowG_geo.choices.global',       target: 'flowG_need', capture: { key: 'geoArea', value: 'Globale' } },
    ],
  },
  {
    id: 'flowG_need',
    clearOnBack: { needType: null },
    showSidebar: true,
    promptKey: 'flowG_need.prompt',
    choices: [
      { labelKey: 'qualification:needType.immediate_project',   target: 'flowG_form', capture: { key: 'needType', value: 'immediate_project' } },
      { labelKey: 'qualification:needType.platform_evaluation', target: 'flowG_form', capture: { key: 'needType', value: 'platform_evaluation' } },
      { labelKey: 'qualification:needType.internal_analysis',   target: 'flowG_form', capture: { key: 'needType', value: 'internal_analysis' } },
      { labelKey: 'qualification:needType.commercial_info',     target: 'flowG_form', capture: { key: 'needType', value: 'commercial_info' } },
    ],
  },
  {
    id: 'flowG_form',
    showSidebar: true,
    component: 'form',
    formType: 'genericRequest',
    formSuccessTarget: 'flowD_thanks',
  },
];
