export const flowCScreens = [
  {
    id: 'flowC',
    clearOnBack: { subjectType: null },
    showSidebar: true,
    autoCapture: { sourceFlow: 'flowC' },
    messageKey: 'flowC.message',
    topChoices: {
      promptKey: 'flowA.topChoices.prompt',
      captureKey: 'subjectType',
      options: [
        { labelKey: 'qualification:subjectType.aziende', value: 'Aziende', icon: '◈' },
        { labelKey: 'qualification:subjectType.persone', value: 'Persone', icon: '❖' },
      ],
    },
    promptKey: 'flowC.prompt',
    choices: [
      { labelKey: 'qualification:role.security_risk',  target: 'flowC_risk' },
      { labelKey: 'qualification:role.legal',          target: 'flowC_legal' },
      { labelKey: 'qualification:role.compliance_aml', target: 'flowC_compliance' },
      { labelKey: 'qualification:role.HR',             target: 'flowC_hr' },
      { labelKey: 'qualification:role.management',     target: 'flowC_board' },
      { labelKey: 'qualification:role.investor',       target: 'flowC_fund' },
      { labelKey: 'qualification:role.other',          target: 'flowC_other' },
    ],
  },
  {
    id: 'flowC_risk',
    clearOnBack: { role: null },
    showSidebar: true,
    autoCapture: { sourceFlow: 'flowC', role: 'security_risk' },
    messageKey: 'flowC_risk.message',
    ctas: [
      { labelKey: 'ui:cta.requestDemo', personalizable: true, action: { type: 'startDemo', role: 'security_risk', selectedPersona: 'Security / Risk', selectedPersonaLabel: 'Security / Risk', sourceFlow: 'flowC', sourceScreen: 'flowC_risk' } },
      { labelKey: 'cta.contactTeam', target: 'flowF' },
    ],
  },
  {
    id: 'flowC_legal',
    clearOnBack: { role: null },
    showSidebar: true,
    autoCapture: { sourceFlow: 'flowC', role: 'legal' },
    messageKey: 'flowC_legal.message',
    ctas: [
      { labelKey: 'ui:cta.requestDemo', personalizable: true, action: { type: 'startDemo', role: 'legal', selectedPersona: 'Legale / Contenzioso', selectedPersonaLabel: 'Professionisti legali', sourceFlow: 'flowC', sourceScreen: 'flowC_legal' } },
      { labelKey: 'cta.contactTeam', target: 'flowF' },
    ],
  },
  {
    id: 'flowC_compliance',
    clearOnBack: { role: null },
    showSidebar: true,
    autoCapture: { sourceFlow: 'flowC', role: 'compliance_aml' },
    messageKey: 'flowC_compliance.message',
    ctas: [
      { labelKey: 'ui:cta.requestDemo', personalizable: true, action: { type: 'startDemo', role: 'compliance_aml', selectedPersona: 'Compliance / AML', selectedPersonaLabel: 'Compliance / AML', sourceFlow: 'flowC', sourceScreen: 'flowC_compliance' } },
      { labelKey: 'cta.commercialContact', target: 'flowF' },
    ],
  },
  {
    id: 'flowC_hr',
    clearOnBack: { role: null },
    showSidebar: true,
    autoCapture: { sourceFlow: 'flowC', role: 'HR' },
    messageKey: 'flowC_hr.message',
    ctas: [
      { labelKey: 'ui:cta.requestDemo', personalizable: true, action: { type: 'startDemo', role: 'HR', selectedPersona: 'HR', selectedPersonaLabel: 'HR', sourceFlow: 'flowC', sourceScreen: 'flowC_hr' } },
      { labelKey: 'cta.contactTeam', target: 'flowF' },
    ],
  },
  {
    id: 'flowC_board',
    clearOnBack: { role: null },
    showSidebar: true,
    autoCapture: { sourceFlow: 'flowC', role: 'management' },
    messageKey: 'flowC_board.message',
    ctas: [
      { labelKey: 'ui:cta.executive', personalizable: true, action: { type: 'startDemo', role: 'management', selectedPersona: 'Direzione / Board', selectedPersonaLabel: 'Direzione / Board', sourceFlow: 'flowC', sourceScreen: 'flowC_board' } },
      { labelKey: 'cta.contactTeam', target: 'flowF' },
    ],
  },
  {
    id: 'flowC_fund',
    clearOnBack: { role: null },
    showSidebar: true,
    autoCapture: { sourceFlow: 'flowC', role: 'investor' },
    messageKey: 'flowC_fund.message',
    ctas: [
      { labelKey: 'ui:cta.requestDemo', personalizable: true, action: { type: 'startDemo', role: 'investor', selectedPersona: 'Investitore / Fondo', selectedPersonaLabel: 'Investitore / Fondo', sourceFlow: 'flowC', sourceScreen: 'flowC_fund' } },
      { labelKey: 'cta.contactTeam', target: 'flowF' },
    ],
  },
  {
    id: 'flowC_other',
    showSidebar: true,
    autoCapture: { sourceFlow: 'flowC' },
    messageKey: 'flowC_other.message',
    component: 'freetext',
    freeTextCaptureKey: 'customRequest',
    freeTextTarget: 'flowG_form',
  },
];
