export const flowDScreens = [
  {
    id: 'flowD_interest',
    showSidebar: true,
    titleKey: 'flowD_interest.title',
    messageKey: 'flowD_interest.message',
    promptKey: 'flowD_interest.prompt',
    choices: [
      { labelKey: 'flowD_interest.choices.dd',           target: 'flowD_role', capture: { key: 'intent', value: 'due_diligence' } },
      { labelKey: 'flowD_interest.choices.counterparty', target: 'flowD_role', capture: { key: 'intent', value: 'counterparty_risk' } },
      { labelKey: 'flowD_interest.choices.reputational', target: 'flowD_role', capture: { key: 'intent', value: 'reputational_risk' } },
      { labelKey: 'flowD_interest.choices.litigation',   target: 'flowD_role', capture: { key: 'intent', value: 'litigation' } },
      { labelKey: 'flowD_interest.choices.corporate',    target: 'flowD_role', capture: { key: 'intent', value: 'corporate_investigations' } },
      { labelKey: 'flowD_interest.choices.aml',          target: 'flowD_role', capture: { key: 'intent', value: 'aml' } },
      { labelKey: 'flowD_interest.choices.general',      target: 'flowD_role', capture: { key: 'intent', value: 'other' } },
    ],
  },
  {
    id: 'flowD_role',
    showSidebar: true,
    messageKey: 'flowD_role.message',
    promptKey: 'flowD_role.prompt',
    choices: [
      { labelKey: 'flowD_role.choices.security_risk', target: 'flowD_org', capture: { key: 'role', value: 'security_risk' } },
      { labelKey: 'flowD_role.choices.legal',         target: 'flowD_org', capture: { key: 'role', value: 'legal' } },
      { labelKey: 'flowD_role.choices.compliance',    target: 'flowD_org', capture: { key: 'role', value: 'compliance_aml' } },
      { labelKey: 'flowD_role.choices.hr',            target: 'flowD_org', capture: { key: 'role', value: 'HR' } },
      { labelKey: 'flowD_role.choices.management',    target: 'flowD_org', capture: { key: 'role', value: 'management' } },
      { labelKey: 'flowD_role.choices.other',         target: 'flowD_org', capture: { key: 'role', value: 'other' } },
    ],
  },
  {
    id: 'flowD_org',
    showSidebar: true,
    messageKey: 'flowD_org.message',
    promptKey: 'flowD_org.prompt',
    choices: [
      { labelKey: 'flowD_org.choices.azienda',             target: 'flowD_timing', capture: { key: 'org', value: 'Azienda' } },
      { labelKey: 'flowD_org.choices.studioLegale',        target: 'flowD_timing', capture: { key: 'org', value: 'Studio legale' } },
      { labelKey: 'flowD_org.choices.istitutoFinanziario', target: 'flowD_timing', capture: { key: 'org', value: 'Istituto finanziario' } },
      { labelKey: 'flowD_org.choices.consulenza',          target: 'flowD_timing', capture: { key: 'org', value: 'Consulenza' } },
      { labelKey: 'flowD_org.choices.fondo',               target: 'flowD_timing', capture: { key: 'org', value: 'Fondo' } },
      { labelKey: 'flowD_org.choices.pubblico',            target: 'flowD_timing', capture: { key: 'org', value: 'Pubblico' } },
      { labelKey: 'flowD_org.choices.other',               target: 'flowD_timing', capture: { key: 'org', value: 'other' } },
    ],
  },
  {
    id: 'flowD_timing',
    showSidebar: true,
    messageKey: 'flowD_timing.message',
    promptKey: 'flowD_timing.prompt',
    choices: [
      { labelKey: 'flowD_timing.choices.immediate',   target: 'flowD_form', capture: { key: 'timing', value: 'Immediate' } },
      { labelKey: 'flowD_timing.choices.within7days', target: 'flowD_form', capture: { key: 'timing', value: 'Entro 7 giorni' } },
      { labelKey: 'flowD_timing.choices.withinMonth', target: 'flowD_form', capture: { key: 'timing', value: 'Entro il mese' } },
      { labelKey: 'flowD_timing.choices.preliminary', target: 'flowD_form', capture: { key: 'timing', value: 'Valutazione preliminare' } },
    ],
  },
  {
    id: 'flowD_form',
    showSidebar: true,
    component: 'form',
    formType: 'demo',
    formSuccessTarget: 'flowD_thanks',
  },
  {
    id: 'flowD_thanks',
    showSidebar: true,
    component: 'thanks',
    messageKey: 'funnel.thanks.message',
  },
];
