export const flowDScreens = [
  {
    id: 'flowD_interest',
    showSidebar: true,
    title: 'Richiedi Demo',
    message: "Posso aiutarti a indirizzare correttamente la richiesta di demo.",
    prompt: "Qual è la tua principale area di interesse?",
    choices: [
      { label: 'Due diligence',           target: 'flowD_role', capture: { key: 'interest', value: 'Due diligence' } },
      { label: 'Rischio controparti',     target: 'flowD_role', capture: { key: 'interest', value: 'Rischio controparti' } },
      { label: 'Rischio reputazionale',   target: 'flowD_role', capture: { key: 'interest', value: 'Rischio reputazionale' } },
      { label: 'Litigation intelligence', target: 'flowD_role', capture: { key: 'interest', value: 'Litigation intelligence' } },
      { label: 'Indagini aziendali',      target: 'flowD_role', capture: { key: 'interest', value: 'Indagini aziendali' } },
      { label: 'AML / KYC',              target: 'flowD_role', capture: { key: 'interest', value: 'AML / KYC' } },
      { label: 'Demo generale',           target: 'flowD_role', capture: { key: 'interest', value: 'Demo generale' } },
    ],
  },
  {
    id: 'flowD_role',
    showSidebar: true,
    message: 'Ogni funzione utilizza DeepSearch con obiettivi e flussi operativi diversi.\nQuesto mi permette di orientare correttamente la sessione.',
    prompt: "Qual è il tuo ruolo?",
    choices: [
      { label: 'Security / Risk',  target: 'flowD_org', capture: { key: 'role', value: 'Security / Risk' } },
      { label: 'Legale',           target: 'flowD_org', capture: { key: 'role', value: 'Legale' } },
      { label: 'Compliance',       target: 'flowD_org', capture: { key: 'role', value: 'Compliance' } },
      { label: 'HR',               target: 'flowD_org', capture: { key: 'role', value: 'HR' } },
      { label: 'Direzione',        target: 'flowD_org', capture: { key: 'role', value: 'Direzione' } },
      { label: 'Altro',            target: 'flowD_org', capture: { key: 'role', value: 'Altro' } },
    ],
  },
  {
    id: 'flowD_org',
    showSidebar: true,
    message: 'Il tipo di organizzazione determina dataset, integrazioni e modello operativo più adatti alla tua realtà.',
    prompt: 'Tipo di organizzazione:',
    choices: [
      { label: 'Azienda',            target: 'flowD_timing', capture: { key: 'org', value: 'Azienda' } },
      { label: 'Studio legale',      target: 'flowD_timing', capture: { key: 'org', value: 'Studio legale' } },
      { label: 'Istituto finanziario',target: 'flowD_timing', capture: { key: 'org', value: 'Istituto finanziario' } },
      { label: 'Consulenza',         target: 'flowD_timing', capture: { key: 'org', value: 'Consulenza' } },
      { label: 'Fondo',              target: 'flowD_timing', capture: { key: 'org', value: 'Fondo' } },
      { label: 'Pubblico',           target: 'flowD_timing', capture: { key: 'org', value: 'Pubblico' } },
      { label: 'Altro',              target: 'flowD_timing', capture: { key: 'org', value: 'Altro' } },
    ],
  },
  {
    id: 'flowD_timing',
    showSidebar: true,
    message: 'Per coordinare al meglio la sessione con il team DeepSearch:',
    prompt: 'Tempistiche:',
    choices: [
      { label: 'Immediate',              target: 'flowD_form', capture: { key: 'timing', value: 'Immediate' } },
      { label: 'Entro 7 giorni',         target: 'flowD_form', capture: { key: 'timing', value: 'Entro 7 giorni' } },
      { label: 'Entro il mese',          target: 'flowD_form', capture: { key: 'timing', value: 'Entro il mese' } },
      { label: 'Valutazione preliminare',target: 'flowD_form', capture: { key: 'timing', value: 'Valutazione preliminare' } },
    ],
  },
  {
    id: 'flowD_form',
    showSidebar: true,
    component: 'form',
    formType: 'demo',
    formSuccessTarget: 'flowD_thanks',
  },
  {
    id: 'flowD_thanks',
    showSidebar: true,
    component: 'thanks',
    message: "Grazie.\nLa richiesta è stata acquisita.\nUn referente DeepSearch ti contatterà entro 24 ore.",
  },
];
